---
cluster_name: kubernetes-cluster-01
master_group: kube-servers
worker_group: kube-nodes
# virtual_ip: "{{ hostvars['kube-load-balancer']['kvm_ip'] }}"
# virtual_port: 64430

master_ip: ""
worker_ip: ""

certificate_dir: /tmp/ansible/kubernetes-certificate
worker_sub_dirs:
  - "certificates/kube-proxy"
  - "certificates/kubelet"

### root CA expired time (20 year)
expireTime: 175200h
### intermediate CA expired time (10 year)
intermediateExpireTime: 87600h
### certificate expired time (1 year)
certificate:
  expireTime: 8760h
city: Ternopil
country: UA
organizationUnit: Kubernetes
province: Ternopil

# cfssl_version: 1.5.0
# cfssl_url: https://github.com/cloudflare/cfssl/releases/download
# local_bin_dir: /usr/local/bin/
