---
time_zone: 'Europe/Kyiv'

default_vg_name: "kvm_vg"
default_lg_name: "kube-server"
kvm_volume_group:
  kvm_vg:
    vg: kvm_vg
    pvs: /dev/nvme1n1
    size:
  vg-libvirt:
    vg: vg-libvirt
    pvs: /dev/nvme0n7
    size:

kvm_logic_volume:
  pangolin:
    vg: kvm_vg
    lv:  pangolin
    size: 20g
  kube-server:
    vg: kvm_vg
    lv:  kube_server
    size: 100g
  kube-server-30:
    vg: kvm_vg
    lv:  kube_server_30
    size: 100g
  kube-node:
    vg: kvm_vg
    lv:  kube_node
    size: 100g
  kube-node-30:
    vg: kvm_vg
    lv:  kube_node_30
    size: 100g
  load-balancer:
    vg: kvm_vg
    lv: load_balancer
    size: 20g
  kube-api-test:
    vg: vg-libvirt
    lv:  kube_api_test
    size: 40g
  kube-nide-test:
    vg: vg-libvirt
    lv:  kube_node_test
    size: 40g
