---
- name: Create kubernates directory
  file:
    path: "{{ kube_cert_dir }}"
    state: directory
    recurse: yes

- name: Copy certificates
  copy:
    src: "{{certificate_dir}}/{{ item }}"
    dest: "{{ kube_cert_dir }}/"
  with_items:
    - "{{ certificate_list }}"

- name: Create symbolic links
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - "{{ certificate_links }}"
  loop_control:
    label: "{{ item.src }}"
