---
- name: Install deb packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install brew packages
  homebrew:
    name: "{{ packages }}"
    state: present
    update_homebrew: yes
  when: ansible_distribution == 'MacOSX'

# - name: Install cfssl and cfssljson
#   get_url:
#     url: "{{ cfssl_url }}/v{{ cfssl_version }}/{{ item }}_{{ cfssl_version }}_linux_amd64"
#     dest: "{{ local_bin_dir }}/{{ item }}"
#     mode: a+x
#   with_items:
#     - cfssl
#     - cfssljson
