---
- name: Create kubeconfig directory
  file:
    path: "{{ certificate_dir }}/kubeconfig"
    state: directory

- name: Generate kubeconfig for admin
  args:
    chdir: "{{ certificate_dir }}/kubeconfig"
  shell: |
    kubectl config set-cluster {{ cluster_name }} \
        --certificate-authority={{ certificate_dir }}/intermediates/kubernetes-ca/kubernetes-ca.pem \
        --embed-certs=true \
        --server=https://127.0.0.1:6443 \
        --kubeconfig=admin.kubeconfig

    kubectl config set-credentials admin \
        --client-certificate={{ certificate_dir }}/certificates/kubernetes-admin/kubernetes-admin.pem \
        --client-key={{ certificate_dir }}/certificates/kubernetes-admin/kubernetes-admin-key.pem \
        --embed-certs=true \
        --kubeconfig=admin.kubeconfig

    kubectl config set-context default \
        --cluster={{ cluster_name }} \
        --user=admin \
        --kubeconfig=admin.kubeconfig

    kubectl config use-context default --kubeconfig=admin.kubeconfig

- name: Generate kubeconfig for kube-controller-manager
  args:
    chdir: "{{ certificate_dir }}/kubeconfig/"
  shell: |
    kubectl config set-cluster {{ cluster_name }} \
        --certificate-authority={{ certificate_dir }}/intermediates/kubernetes-ca/kubernetes-ca.pem \
        --embed-certs=true \
        --server=https://127.0.0.1:6443 \
        --kubeconfig=kube-controller-manager.kubeconfig

    kubectl config set-credentials system:kube-controller-manager \
        --client-certificate={{ certificate_dir }}/certificates/kube-controller-manager/kube-controller-manager.pem \
        --client-key={{ certificate_dir }}/certificates/kube-controller-manager/kube-controller-manager-key.pem \
        --embed-certs=true \
        --kubeconfig=kube-controller-manager.kubeconfig

    kubectl config set-context default \
        --cluster={{ cluster_name }} \
        --user=system:kube-controller-manager \
        --kubeconfig=kube-controller-manager.kubeconfig

    kubectl config use-context default --kubeconfig=kube-controller-manager.kubeconfig

- name: Generate kubeconfig for kube-scheduler
  args:
    chdir: "{{ certificate_dir }}/kubeconfig/"
  shell: |
    kubectl config set-cluster {{ cluster_name }} \
        --certificate-authority={{ certificate_dir }}/intermediates/kubernetes-ca/kubernetes-ca.pem \
        --embed-certs=true \
        --server=https://127.0.0.1:6443 \
        --kubeconfig=kube-scheduler.kubeconfig

    kubectl config set-credentials system:kube-scheduler \
        --client-certificate={{ certificate_dir }}/certificates/kube-scheduler/kube-scheduler.pem \
        --client-key={{ certificate_dir }}/certificates/kube-scheduler/kube-scheduler-key.pem \
        --embed-certs=true \
        --kubeconfig=kube-scheduler.kubeconfig

    kubectl config set-context {{ cluster_name }} \
        --cluster={{ cluster_name }} \
        --user=system:kube-scheduler \
        --kubeconfig=kube-scheduler.kubeconfig

    kubectl config use-context {{ cluster_name }} --kubeconfig=kube-scheduler.kubeconfig
